// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Tests for the image extraction API.
//
// Sections:
//   1. Unit tests for image value types (PdfColorspace, PdfImageMetadata,
//      PdfImage, PdfImageBitmap, PdfPageImages).
//   2. Integration tests against fixture PDFs via the native PDFium backend.
//      Skipped when the PDFium dylib is not present.
//
// Fixture PDFs are generated by:
//   python3 test/fixtures/generate/generate_fixtures.py

import 'dart:io';
import 'dart:typed_data';

import 'package:test/test.dart';

import 'package:betto_pdfium/betto_pdfium.dart';
import 'package:betto_pdfium/src/document/pdfium_isolate.dart'
    show PdfiumIsolate;

import 'native_test_helper.dart';

/// Reads a fixture file from test/fixtures/.
Uint8List _readFixture(String name) {
  final file = File('test/fixtures/$name');
  if (!file.existsSync()) {
    throw StateError(
      'Test fixture not found: test/fixtures/$name. '
      'Run python3 test/fixtures/generate/generate_fixtures.py',
    );
  }
  return file.readAsBytesSync();
}

void main() {
  // -------------------------------------------------------------------------
  // 1. Unit tests for image value types
  // -------------------------------------------------------------------------

  group('PdfColorspace', () {
    test('has all expected values', () {
      expect(PdfColorspace.values.length, equals(12));
      expect(PdfColorspace.unknown, isNotNull);
      expect(PdfColorspace.deviceGray, isNotNull);
      expect(PdfColorspace.deviceRgb, isNotNull);
      expect(PdfColorspace.deviceCmyk, isNotNull);
    });
  });

  group('PdfImageMetadata', () {
    const meta = PdfImageMetadata(
      width: 100,
      height: 200,
      horizontalDpi: 72.0,
      verticalDpi: 72.0,
      bitsPerPixel: 24,
      colorspace: PdfColorspace.deviceRgb,
      markedContentId: -1,
    );

    test('equality: same values are equal', () {
      const other = PdfImageMetadata(
        width: 100,
        height: 200,
        horizontalDpi: 72.0,
        verticalDpi: 72.0,
        bitsPerPixel: 24,
        colorspace: PdfColorspace.deviceRgb,
        markedContentId: -1,
      );
      expect(meta, equals(other));
    });

    test('equality: different width is not equal', () {
      const other = PdfImageMetadata(
        width: 50,
        height: 200,
        horizontalDpi: 72.0,
        verticalDpi: 72.0,
        bitsPerPixel: 24,
        colorspace: PdfColorspace.deviceRgb,
        markedContentId: -1,
      );
      expect(meta, isNot(equals(other)));
    });

    test('hashCode: equal objects have equal hashCodes', () {
      const other = PdfImageMetadata(
        width: 100,
        height: 200,
        horizontalDpi: 72.0,
        verticalDpi: 72.0,
        bitsPerPixel: 24,
        colorspace: PdfColorspace.deviceRgb,
        markedContentId: -1,
      );
      expect(meta.hashCode, equals(other.hashCode));
    });

    test('hashCode: different objects have different hashCodes (typically)', () {
      const other = PdfImageMetadata(
        width: 50,
        height: 200,
        horizontalDpi: 72.0,
        verticalDpi: 72.0,
        bitsPerPixel: 24,
        colorspace: PdfColorspace.deviceGray,
        markedContentId: 5,
      );
      // Not guaranteed by contract but almost always true for distinct values.
      expect(meta.hashCode, isNot(equals(other.hashCode)));
    });

    test('toString includes key fields', () {
      final s = meta.toString();
      expect(s, contains('width: 100'));
      expect(s, contains('height: 200'));
      expect(s, contains('deviceRgb'));
      expect(s, contains('markedContentId: -1'));
    });
  });

  group('PdfImage', () {
    const meta = PdfImageMetadata(
      width: 64,
      height: 48,
      horizontalDpi: 96.0,
      verticalDpi: 96.0,
      bitsPerPixel: 24,
      colorspace: PdfColorspace.deviceRgb,
      markedContentId: -1,
    );
    const bounds = PdfRect(left: 10, bottom: 10, right: 90, top: 70);

    test('bitmap fields are null when not requested', () {
      const img = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
      );
      expect(img.bgra, isNull);
      expect(img.bitmapWidth, isNull);
      expect(img.bitmapHeight, isNull);
    });

    test('bitmap fields are non-null when provided', () {
      final bgra = Uint8List(64 * 48 * 4);
      final img = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
        bgra: bgra,
        bitmapWidth: 64,
        bitmapHeight: 48,
      );
      expect(img.bgra, isNotNull);
      expect(img.bitmapWidth, equals(64));
      expect(img.bitmapHeight, equals(48));
    });

    test('hashCode: equal objects have equal hashCodes', () {
      final bgra = Uint8List(64 * 48 * 4);
      final img1 = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
        bgra: bgra,
        bitmapWidth: 64,
        bitmapHeight: 48,
      );
      final img2 = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
        bgra: bgra,
        bitmapWidth: 64,
        bitmapHeight: 48,
      );
      expect(img1.hashCode, equals(img2.hashCode));
    });

    test('equality ignores bgra buffer content', () {
      // Two PdfImages with the same geometry but different bgra buffers should
      // be equal (bgra is excluded from equality to avoid O(n) byte comparison).
      final bgra1 = Uint8List(64 * 48 * 4)..fillRange(0, 64 * 48 * 4, 0xFF);
      final bgra2 = Uint8List(64 * 48 * 4)..fillRange(0, 64 * 48 * 4, 0x00);
      final img1 = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
        bgra: bgra1,
        bitmapWidth: 64,
        bitmapHeight: 48,
      );
      final img2 = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
        bgra: bgra2,
        bitmapWidth: 64,
        bitmapHeight: 48,
      );
      expect(img1, equals(img2));
    });

    test('toString includes key fields', () {
      const img = PdfImage(
        pageIndex: 0,
        objectIndex: 2,
        metadata: meta,
        bounds: bounds,
        filters: ['DCTDecode'],
      );
      final s = img.toString();
      expect(s, contains('pageIndex: 0'));
      expect(s, contains('objectIndex: 2'));
      expect(s, contains('DCTDecode'));
    });
  });

  group('PdfImageBitmap', () {
    test('equality based on width and height only', () {
      final a = PdfImageBitmap(bgra: Uint8List(4), width: 1, height: 1);
      final b = PdfImageBitmap(bgra: Uint8List(4), width: 1, height: 1);
      expect(a, equals(b));
    });

    test('hashCode: equal objects have equal hashCodes', () {
      final a = PdfImageBitmap(bgra: Uint8List(4), width: 1, height: 1);
      final b = PdfImageBitmap(bgra: Uint8List(4), width: 1, height: 1);
      expect(a.hashCode, equals(b.hashCode));
    });

    test('inequality when dimensions differ', () {
      final a = PdfImageBitmap(bgra: Uint8List(4), width: 1, height: 1);
      final b = PdfImageBitmap(bgra: Uint8List(16), width: 2, height: 2);
      expect(a, isNot(equals(b)));
    });

    test('toString includes dimensions and byte count', () {
      final bmp = PdfImageBitmap(bgra: Uint8List(256), width: 8, height: 8);
      final s = bmp.toString();
      expect(s, contains('width: 8'));
      expect(s, contains('height: 8'));
      expect(s, contains('256 bytes'));
    });
  });

  group('PdfPageImages', () {
    test('toString includes page index and image count', () {
      const ppi = PdfPageImages(pageIndex: 3, images: []);
      expect(ppi.toString(), contains('pageIndex: 3'));
      expect(ppi.toString(), contains('images: 0'));
    });
  });

  // -------------------------------------------------------------------------
  // 2. Integration tests (require native PDFium dylib)
  // -------------------------------------------------------------------------

  group('image extraction integration', () {
    late PdfDocument doc;

    setUp(() async {
      if (!nativeAvailable()) return;
      // Reset isolate state between test groups to avoid cross-test pollution.
      PdfiumIsolate.resetForTesting();
    });

    tearDown(() async {
      if (!nativeAvailable()) return;
      try {
        await doc.close();
      } catch (_) {
        // Already closed in some tests; ignore.
      }
      PdfiumIsolate.resetForTesting();
    });

    // Helper: open a fixture document.
    Future<PdfDocument> openFixture(String name) async {
      return PdfDocument.fromBytes(
        _readFixture(name),
        dylibPath: nativeDylibPath(),
      );
    }

    test('page with no images returns empty list', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('no_images.pdf');
      final pages = await doc.extractImages().toList();
      expect(pages, hasLength(1));
      expect(pages.first.pageIndex, equals(0));
      expect(pages.first.images, isEmpty);
    });

    test('extractImages yields one PdfPageImages per page', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('multi_image.pdf');
      final pages = await doc.extractImages().toList();
      // multi_image.pdf has 2 pages.
      expect(pages, hasLength(2));
      expect(pages[0].pageIndex, equals(0));
      expect(pages[1].pageIndex, equals(1));
    });

    test('page 0 of multi_image.pdf has 2 images', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('multi_image.pdf');
      final pages = await doc.extractImages().toList();
      expect(pages[0].images, hasLength(2));
    });

    test('image metadata fields are populated correctly', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      final pages = await doc.extractImages().toList();
      expect(pages, hasLength(1));
      expect(pages.first.images, hasLength(1));

      final img = pages.first.images.first;
      expect(img.pageIndex, equals(0));
      expect(img.objectIndex, greaterThanOrEqualTo(0));

      // The PNG is 64x48 source pixels.
      expect(img.metadata.width, equals(64));
      expect(img.metadata.height, equals(48));
      // DPI must be positive (fpdf2 sets a default DPI).
      expect(img.metadata.horizontalDpi, greaterThan(0));
      expect(img.metadata.verticalDpi, greaterThan(0));
      // bitsPerPixel must be positive.
      expect(img.metadata.bitsPerPixel, greaterThan(0));
    });

    test(
      'extractImages(includeBitmap: false) — bitmap fields are null',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('single_image.pdf');
        final pages = await doc.extractImages(includeBitmap: false).toList();
        final img = pages.first.images.first;
        expect(img.bgra, isNull);
        expect(img.bitmapWidth, isNull);
        expect(img.bitmapHeight, isNull);
      },
    );

    test(
      'extractImages(includeBitmap: true) — BGRA bytes have expected length',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('single_image.pdf');
        final pages = await doc.extractImages(includeBitmap: true).toList();
        final img = pages.first.images.first;
        // When includeBitmap is true, rendered bitmap fields must be non-null.
        expect(img.bitmapWidth, isNotNull);
        expect(img.bitmapHeight, isNotNull);
        expect(img.bgra, isNotNull);
        // BGRA byte length must equal bitmapWidth * bitmapHeight * 4.
        expect(
          img.bgra!.length,
          equals(img.bitmapWidth! * img.bitmapHeight! * 4),
        );
      },
    );

    test('bounds rect is non-zero for a visible image', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      final pages = await doc.extractImages().toList();
      final img = pages.first.images.first;
      // The image was placed at x=20, y=20 with w=80mm — bounds must be > 0.
      final b = img.bounds;
      expect(b.right, greaterThan(b.left));
      expect(b.top, isNot(equals(b.bottom)));
    });

    test(
      'renderImage returns a PdfImageBitmap with correct dimensions',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('single_image.pdf');
        final pages = await doc.extractImages().toList();
        final img = pages.first.images.first;
        final bitmap = await doc.renderImage(img.pageIndex, img.objectIndex);
        expect(bitmap, isNotNull);
        expect(bitmap!.width, greaterThan(0));
        expect(bitmap.height, greaterThan(0));
        expect(bitmap.bgra.length, equals(bitmap.width * bitmap.height * 4));
      },
    );

    test('renderImage dimensions match includeBitmap dimensions', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      // Get dimensions via extractImages(includeBitmap: true).
      final pages = await doc.extractImages(includeBitmap: true).toList();
      final img = pages.first.images.first;
      // renderImage should produce the same dimensions.
      final bitmap = await doc.renderImage(img.pageIndex, img.objectIndex);
      expect(bitmap, isNotNull);
      expect(bitmap!.width, equals(img.bitmapWidth));
      expect(bitmap.height, equals(img.bitmapHeight));
    });

    test('renderImage throws RangeError for out-of-range page index', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      await expectLater(() => doc.renderImage(99, 0), throwsRangeError);
    });

    test('renderImage throws RangeError for negative object index', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      await expectLater(() => doc.renderImage(0, -1), throwsRangeError);
    });

    test('renderImage returns null for out-of-range object index', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      // Use an object index that is definitely beyond any real object.
      final result = await doc.renderImage(0, 9999);
      expect(result, isNull);
    });

    test('renderImage throws StateError after close()', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      final closedDoc = await openFixture('single_image.pdf');
      await closedDoc.close();
      await expectLater(() => closedDoc.renderImage(0, 0), throwsStateError);
    });

    test(
      'extractImages throws RangeError for out-of-range pageIndex',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('single_image.pdf');
        await expectLater(
          () => doc.extractImages(pageIndex: 99).toList(),
          throwsRangeError,
        );
      },
    );

    test(
      'close() during active extractImages stream terminates cleanly',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('multi_image.pdf');
        final results = <PdfPageImages>[];
        // Collect pages but close the document after the first yield.
        await for (final page in doc.extractImages()) {
          results.add(page);
          // Close the document mid-stream; the stream should stop cleanly.
          await doc.close();
        }
        // Only the first page should have been collected before close.
        expect(results, hasLength(1));
      },
    );

    test('image mask objects (1bpp) appear in output', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      // Use scanned.pdf which embeds a greyscale PNG; PDFium may surface
      // its mask channel as a 1bpp object depending on the PDF structure.
      // The key assertion is that the stream doesn't crash regardless of
      // mask presence; we verify the stream completes without error.
      doc = await openFixture('scanned.pdf');
      final pages = await doc.extractImages().toList();
      expect(pages, hasLength(1));
      // scanned.pdf has at least one image (the embedded PNG).
      expect(pages.first.images, isNotEmpty);
    });

    test('filter list is populated for a JPEG or PNG encoded image', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('single_image.pdf');
      final pages = await doc.extractImages().toList();
      final img = pages.first.images.first;
      // fpdf2 embeds PNG images with FlateDecode (or DCTDecode for JPEG).
      // The filters list should be non-empty for compressed image data.
      // We assert non-empty; the specific filter name depends on fpdf2's encoder.
      expect(img.filters, isNotEmpty);
    });

    test(
      'extractImages with single pageIndex returns only that page',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('multi_image.pdf');
        final pages = await doc.extractImages(pageIndex: 1).toList();
        expect(pages, hasLength(1));
        expect(pages.first.pageIndex, equals(1));
      },
    );

    test('extractImages throws StateError after close()', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      final closedDoc = await openFixture('single_image.pdf');
      await closedDoc.close();
      expect(() => closedDoc.extractImages().toList(), throwsStateError);
    });

    test(
      'broken_image_metadata.pdf — streamless XObject is skipped gracefully',
      () async {
        // Covers the skip path at pdfium_isolate.dart ~lines 2039-2042:
        // FPDFImageObj_GetImageMetadata returns false for a dict-only image
        // XObject (no stream … endstream body), and the isolate continues
        // without throwing.
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('broken_image_metadata.pdf');
        // The fixture has one page with one image XObject, but the XObject
        // has no stream body — PDFium cannot read its metadata and the
        // isolate skips it.  extractImages() must complete without throwing.
        final pages = await doc.extractImages().toList();
        expect(pages, hasLength(1));
        // The malformed image object is skipped, so the page reports 0 images.
        expect(
          pages.first.images,
          isEmpty,
          reason:
              'The streamless XObject should be silently skipped, '
              'yielding zero images for the page',
        );
      },
    );
  });
}
