// Copyright 2026 The Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Integration tests for the annotation extraction API (PdfDocument.extractAnnotations).
//
// These tests require the native PDFium dylib. They are skipped gracefully when
// the binary is absent (same pattern as image_extraction_test.dart).
//
// Fixture PDFs are generated by:
//   python3 test/fixtures/generate/generate_fixtures.py
//
// Reference .annot.json files describe expected annotation counts and types.

import 'dart:io';
import 'dart:typed_data';

import 'package:test/test.dart';

import 'package:betto_pdfium/betto_pdfium.dart';
import 'package:betto_pdfium/src/document/pdfium_isolate.dart'
    show PdfiumIsolate;

import 'native_test_helper.dart';

/// Reads a fixture file from test/fixtures/.
Uint8List _readFixture(String name) {
  final file = File('test/fixtures/$name');
  if (!file.existsSync()) {
    throw StateError(
      'Test fixture not found: test/fixtures/$name. '
      'Run python3 test/fixtures/generate/generate_fixtures.py',
    );
  }
  return file.readAsBytesSync();
}

void main() {
  group('annotation extraction integration', () {
    late PdfDocument doc;

    setUp(() async {
      if (!nativeAvailable()) return;
      PdfiumIsolate.resetForTesting();
    });

    tearDown(() async {
      if (!nativeAvailable()) return;
      try {
        await doc.close();
      } catch (_) {
        // Already closed in some tests; ignore.
      }
      PdfiumIsolate.resetForTesting();
    });

    /// Opens a fixture PDF using the native dylib path.
    Future<PdfDocument> openFixture(String name) async {
      return PdfDocument.fromBytes(
        _readFixture(name),
        dylibPath: nativeDylibPath(),
      );
    }

    // -------------------------------------------------------------------------
    // no_annotations.pdf
    // -------------------------------------------------------------------------

    test(
      'no_annotations.pdf — stream yields one PdfPageAnnotations with empty list',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('no_annotations.pdf');
        final pages = await doc.extractAnnotations().toList();
        expect(pages, hasLength(1));
        expect(pages.first.pageIndex, equals(0));
        expect(pages.first.annotations, isEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // annotated_text.pdf — PdfTextAnnotation + PdfMarkupAnnotation
    // -------------------------------------------------------------------------

    test(
      'annotated_text.pdf — first page has 3 annotations (highlight, text, underline)',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_text.pdf');
        final pages = await doc.extractAnnotations().toList();
        expect(pages, hasLength(1));
        final annots = pages.first.annotations;
        // Reference: annotated_text.annot.json has 3 annotations.
        expect(annots, hasLength(3));
      },
    );

    test(
      'annotated_text.pdf — contains a PdfTextAnnotation (sticky note)',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_text.pdf');
        final pages = await doc.extractAnnotations().toList();
        final annots = pages.first.annotations;
        final textAnnot = annots.whereType<PdfTextAnnotation>().toList();
        expect(textAnnot, isNotEmpty);
        // Verify common fields are populated.
        final a = textAnnot.first;
        expect(a.pageIndex, equals(0));
        expect(a.contents, isNotNull);
        expect(a.rect, isNotNull);
      },
    );

    test(
      'annotated_text.pdf — contains a PdfMarkupAnnotation (highlight)',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_text.pdf');
        final pages = await doc.extractAnnotations().toList();
        final annots = pages.first.annotations;
        final highlights = annots
            .whereType<PdfMarkupAnnotation>()
            .where((a) => a.subtype == PdfAnnotationType.highlight)
            .toList();
        expect(highlights, isNotEmpty);
        final h = highlights.first;
        expect(h.rect, isNotNull);
        expect(h.color, isNotNull);
        expect(h.flags, isNonNegative);
      },
    );

    // -------------------------------------------------------------------------
    // annotated_shapes.pdf — PdfShapeAnnotation, PdfLineAnnotation
    // -------------------------------------------------------------------------

    test(
      'annotated_shapes.pdf — contains PdfShapeAnnotation with expected subtype',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_shapes.pdf');
        final pages = await doc.extractAnnotations().toList();
        expect(pages, hasLength(1));
        // Reference: annotated_shapes.annot.json has 3 annotations (Square, Circle, Line).
        expect(pages.first.annotations, hasLength(3));
        final shapes = pages.first.annotations
            .whereType<PdfShapeAnnotation>()
            .toList();
        expect(shapes, isNotEmpty);
        final subtypes = shapes.map((s) => s.subtype).toSet();
        expect(subtypes, contains(PdfAnnotationType.square));
      },
    );

    // -------------------------------------------------------------------------
    // annotated_ink.pdf — PdfInkAnnotation
    // -------------------------------------------------------------------------

    test(
      'annotated_ink.pdf — contains PdfInkAnnotation with non-empty strokes',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_ink.pdf');
        final pages = await doc.extractAnnotations().toList();
        expect(pages, hasLength(1));
        final inkAnnots = pages.first.annotations
            .whereType<PdfInkAnnotation>()
            .toList();
        expect(inkAnnots, isNotEmpty);
        // The ink fixture has at least one stroke.
        expect(inkAnnots.first.strokes, isNotEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // zero_ink_stroke.pdf — guard at isolate ~line 1053
    // -------------------------------------------------------------------------

    test(
      'zero_ink_stroke.pdf — ink annotation with zero-point stroke is returned',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('zero_ink_stroke.pdf');
        final pages = await doc.extractAnnotations().toList();
        // Extraction must complete without throwing.
        expect(pages, hasLength(1));
        // The ink annotation exists but its stroke has 0 points.
        final inkAnnots = pages.first.annotations
            .whereType<PdfInkAnnotation>()
            .toList();
        expect(inkAnnots, isNotEmpty);
        // The zero-point stroke is returned as an empty list within strokes.
        expect(inkAnnots.first.strokes, isNotEmpty);
        expect(inkAnnots.first.strokes.first, isEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // zero_polygon_vertices.pdf — guard at isolate ~line 1085
    // -------------------------------------------------------------------------

    test(
      'zero_polygon_vertices.pdf — polygon with empty vertices does not throw',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('zero_polygon_vertices.pdf');
        final pages = await doc.extractAnnotations().toList();
        expect(pages, hasLength(1));
        // The polygon annotation exists; its vertices list may be empty.
        final polygons = pages.first.annotations
            .whereType<PdfPolygonAnnotation>()
            .toList();
        expect(polygons, isNotEmpty);
        expect(polygons.first.vertices, isEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // popup_annotation.pdf — PdfTextAnnotation with a non-null popup
    // -------------------------------------------------------------------------

    test(
      'popup_annotation.pdf — annotation has a non-null popup field',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('popup_annotation.pdf');
        final pages = await doc.extractAnnotations().toList();
        final allAnnots = pages.expand((p) => p.annotations).toList();
        // At least one annotation should have a popup (exercises _withPopup).
        final withPopup = allAnnots.where((a) => a.popup != null).toList();
        expect(withPopup, isNotEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // popup_freetext.pdf — PdfFreeTextAnnotation with a non-null popup
    // -------------------------------------------------------------------------

    test(
      'popup_freetext.pdf — PdfFreeTextAnnotation has a non-null popup',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('popup_freetext.pdf');
        final pages = await doc.extractAnnotations().toList();
        final allAnnots = pages.expand((p) => p.annotations).toList();
        final freeTextWithPopup = allAnnots
            .whereType<PdfFreeTextAnnotation>()
            .where((a) => a.popup != null)
            .toList();
        expect(freeTextWithPopup, isNotEmpty);
      },
    );

    // -------------------------------------------------------------------------
    // popup_multi.pdf — multiple annotations have popups
    // -------------------------------------------------------------------------

    test('popup_multi.pdf — multiple annotations have popups', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      doc = await openFixture('popup_multi.pdf');
      final pages = await doc.extractAnnotations().toList();
      final allAnnots = pages.expand((p) => p.annotations).toList();
      final withPopup = allAnnots.where((a) => a.popup != null).toList();
      expect(withPopup.length, greaterThan(1));
    });

    // -------------------------------------------------------------------------
    // Single pageIndex argument
    // -------------------------------------------------------------------------

    test(
      'extractAnnotations with single pageIndex returns only that page',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_text.pdf');
        final pages = await doc.extractAnnotations(pageIndex: 0).toList();
        expect(pages, hasLength(1));
        expect(pages.first.pageIndex, equals(0));
      },
    );

    // -------------------------------------------------------------------------
    // Out-of-range pageIndex
    // -------------------------------------------------------------------------

    test(
      'extractAnnotations throws RangeError for out-of-range pageIndex',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        doc = await openFixture('annotated_text.pdf');
        await expectLater(
          () => doc.extractAnnotations(pageIndex: 99).toList(),
          throwsRangeError,
        );
      },
    );

    // -------------------------------------------------------------------------
    // StateError after close()
    // -------------------------------------------------------------------------

    test('extractAnnotations throws StateError after close()', () async {
      if (!nativeAvailable()) {
        markTestSkipped('PDFium dylib not present');
        return;
      }
      final closedDoc = await openFixture('no_annotations.pdf');
      await closedDoc.close();
      expect(() => closedDoc.extractAnnotations().toList(), throwsStateError);
    });

    // -------------------------------------------------------------------------
    // close() during active stream
    // -------------------------------------------------------------------------

    test(
      'close() during active extractAnnotations stream terminates cleanly',
      () async {
        if (!nativeAvailable()) {
          markTestSkipped('PDFium dylib not present');
          return;
        }
        // Use a multi-page annotated fixture so the stream has more than one
        // iteration to work with.
        doc = await openFixture('multi_page_annotated.pdf');
        final results = <PdfPageAnnotations>[];
        await for (final page in doc.extractAnnotations()) {
          results.add(page);
          // Close mid-stream after the first page.
          await doc.close();
        }
        // Only the first page should have been collected before close.
        expect(results, hasLength(1));
      },
    );
  });
}
